### ISSUE TITLE
Maybe not support lb?

### ISSUE THREAD

**Issue by ghost** [benwilcock/spring-cloud-gateway-demo#12]
the gateway application.yml as follow:
```yaml
spring:
  cloud:
    gateway:
      routes:
        - id: resource
          uri: lb://resource:9000
          predicates:
            - Path=/resource
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
```
